// @flow
import type { rollup } from 'rollup';

/** Simulate import from bundle/code generated by rollup
 * @param bundle output of rollup.rollup
 * @example const importedCode = await require(rollup({input, plugins}))
 */
export default (async function require(bundle: rollup) {
  const { code } = await bundle.generate({ format: 'cjs' });
  return eval(code);
});
